name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    # Use Windows 2022 specifically to get VS2022, which allows downloading pre-built binaries from conan center, rather than rebuilding them in CI.
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: ['Debug','Release']

    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@v1.0

      - name: Print Conan version
        run: echo "Using Conan ${{ steps.conan.outputs.version }}"

      - name: Create default Conan profile
        run: conan profile detect

      - name: Build project in ${{ matrix.build_type }} mode
        run: conan create . -s compiler.cppstd=17 -s "&:build_type=${{ matrix.build_type }}" -s build_type=Release --build=missing
